### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by jec324** [the-rebel-Mermaid/BlizzMove#39] opened 2020-10-15 19:05 UTC
Feature Request: 

Save frame position for map on logging out/in.

Thanks

**Comment by Numynum** [comment] 2020-10-15 20:06
duplicate of https://github.com/the-rebel-Mermaid/BlizzMove/issues/26
it's something we might do later on, if we can prevent glitches

**Closed by Numynum** 2020-10-15 20:06 UTC
